# Site settings
title: Frida Melin
email: fm222gn@student.lnu.se
description: Copyright Â© Frida Melin 2016




baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  fm222gn

# Build settings
markdown: kramdown
