# Site settings
title: Frida Melin
email: fm222gn@student.lnu.se
description: Copyright Â© Frida Melin 2016




baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fridamelin.github.io
twitter_username: MelinFrida
github_username:  fridamelin

# Build settings
markdown: kramdown
